apiVersion: v1
kind: Service
metadata:
  name: lrm-model-deployment
spec:
  type: LoadBalancer
  selector:
    app: lrm-model-deployment
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
